- hosts: desktops
  become: true
  vars_files:
    - "config.yml"
  handlers:
    - name: Import handlers.
      ansible.builtin.import_tasks: handlers.yml
  tasks:
    - name: Setup Docker.
      ansible.builtin.import_tasks: tasks/docker.yml
    - name: Setup LaTeX.
      ansible.builtin.import_tasks: tasks/latex.yml
    - name: Setup ssh server.
      ansible.builtin.import_role:
        name: f_koehler.sshd
    - name: Setup haveged.
      ansible.builtin.import_role:
        name: f_koehler.haveged
    - name: Setup kvm.
      ansible.builtin.import_tasks: tasks/kvm.yml
